### ISSUE TITLE
ThemePackage.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by mpancorbo** [circuitfox/bonfire-syntax#7]
Store package style sheets in the  styles/  directory instead of  stylesheets/  in the  bonfire-syntax  package     ThemePackage.getStylesheetsPath  /usr/local/share/atom/resources/app.asar/src/package.js:458:9  unknown>  /usr/local/share/atom/resources/app.asar/src/theme-manager.js:434:35  ThemeManager.getImportPaths  /usr/local/share/atom/resources/app.asar/src/theme-manager.js:438:11  ThemeManager.refreshLessCache  /usr/local/share/atom/resources/app.asar/src/theme-manager.js:421:75  unknown>  /usr/local/share/atom/resources/app.asar/src/theme-manager.js:368:19  _fulfilled  /usr/local/share/atom/resources/app.asar/node_modules/q/q.js:794:54

**Comment by mpancorbo** [comment]
Thanks!

All these issues were launched from my atom instance. Your syntax theme is my favourite!

**Comment by circuitfox** [comment]
If any other issues come up, feel free to let me know. I don't use Atom much anymore so I won't be actively maintaining this, but I will fix any deprecation warnings if they come up.
